import LocalizedStrings from "react-localization";

export const RESTART_ON_REMOUNT = "@@saga-injector/restart-on-remount";
export const DAEMON = "@@saga-injector/daemon";
export const ONCE_TILL_UNMOUNT = "@@saga-injector/once-till-unmount";

export const TEST_URL = "http://123.176.103.187:8092/popared/api"; //'/popared/brand'; //
// export const TEST_URL = 'http://123.176.103.187:8090/popared/api'
//export const TEST_URL = 'https://tiyurenmaiquan.cn/popared/api';

export const stripeToken =
  "pk_live_51H812zE8nBld2orWHSSSEOJ09KREWUj0wz3c34TbLl6JCSfTnmWOJ6qUhn5dHCfBtpCzmXqwhhXb2bfn7vkui62U00x0Qo9qdv";

export const imageUrls = [
  "http://lh3.googleusercontent.com/oK0RNpLseknw0qHGy_DV6xHzB1Wmc4oLZYK32PleRLgQCLpL67UERNFIkkps6ZnNbTb_OD_v4lqQ4a-N3jtQnXQf",
  "http://lh3.googleusercontent.com/LMxlEXIta6S0Y9-MGnVacCCx66HndHnt2JCbDdb8NLvmllzV3iuCwJEBTV5ZfN9TD7AZtR9-SoSnBh36CRkCEXt_xA",
  "https://storage.googleapis.com/revfluenceapp.appspot.com/image/media_content/5263322367131648_1486689226.27",
  "https://storage.googleapis.com/revfluenceapp.appspot.com/image/media_content/5263322367131648_1486689226.27",
  "https://storage.googleapis.com/revfluenceapp.appspot.com/image/media_content/5263322367131648_1486689226.27",
  "http://lh3.googleusercontent.com/R-a-fa73SVbFebtaeQ4yhjsHzELlAOGQxnH0eOYCHcInXv3M60jcNM34Ff7ViSoVuGXfBjGoibpIV4WXgarOUY0O-A",
  "http://lh3.googleusercontent.com/jBixc33rwvMrVDYOyDMZm6N0qjaGc3HhcDXeHj7y23OCP_rApWWkFahuhRrlmeFGyhD4rZbXRTQ5jO-iBqLgApO0784",
  "http://lh3.googleusercontent.com/c0h5qsfil7fqUHpiCfVyeBTZz_xPS-ah3BPb2mdK8DN2SDZ_1SVZcC_XljvrY5vg86mmLlgjUZs-E2qmvM4kxNRRcg",
  "https://storage.googleapis.com/revfluenceapp.appspot.com/image/media_content/4708196275585024_1568814139.72",
  "http://lh3.googleusercontent.com/Rq2XdZQAJh8aRElbaq2YtTFTTZqxWESV6dqTzsP4U13fqbaoB2JpH_tSbLOGDLctTNAFAwdS4EQUbGxksLldy2ftUA",
  // eslint-disable-next-line global-require
  require("../images/default_avatar.png"),
];
export const RIGHT_CONTAINER_DATA = [
  {
    id: 1,
    name: "Ryan Kasley",
    title:
      "Thanks for the info. Your order has been placed for Friday 1/13 delivery, and will include the Rapid Crispy Shrimp tacos. ",
    title1: "hangrydiary@gmail.com",
    title3:
      "Also, here is your discount code to share with your followers. It will get them $35 off their first box (for new customers).",
    date: "01/22/2019 (40w ago)",
    image: imageUrls[1],
    type: "otherMessage",
  },
  {
    id: 1,
    title: "Hi there, our paypal for payment is ",
    title1: "hangrydiary@gmail.com",
    date: "01/22/2019 (40w ago)",
    image: imageUrls[2],
    name: "handrydiary",
    type: "myMessage",
  },
  {
    id: 1,
    title: "A payment of $450.00 is being processed.",
    title1: "",
    date: "01/22/2019 (40w ago)",
    // eslint-disable-next-line global-require
    image: require("../images/dollarIcon.svg"),
    type: "payment",
  },
  {
    id: 2,
    title: "hangrydiary submitted ",
    title1: "proposal to collaborate !",
    date: "01/22/2019 (40w ago)",
    // eslint-disable-next-line global-require
    image: require("../images/dollarIcon.svg"),
    type: "payment",
  },
  {
    id: 3,
    title: "hangrydiary submitted ",
    title1: "proposal to collaborate !",
    date: "01/22/2019 (40w ago)",
    // eslint-disable-next-line global-require
    image: require("../images/dollarIcon.svg"),
    type: "payment",
  },

  {
    id: 4,
    title: "hangrydiary submitted ",
    title1: "proposal to collaborate !",
    date: "01/22/2019 (40w ago)",
    // eslint-disable-next-line global-require
    image: require("../images/dollarIcon.svg"),
    type: "payment",
  },
  {
    id: 4,
    title: "hangrydiary submitted ",
    title1: "proposal to collaborate !",
    date: "01/22/2019 (40w ago)",
    // eslint-disable-next-line global-require
    image: require("../images/dollarIcon.svg"),
    type: "payment",
  },
  {
    id: 4,
    title: "hangrydiary submitted ",
    title1: "proposal to collaborate !",
    date: "01/22/2019 (40w ago)",
    // eslint-disable-next-line global-require
    image: require("../images/dollarIcon.svg"),
    type: "payment",
  },
  {
    id: 4,
    title: "hangrydiary submitted ",
    title1: "proposal to collaborate !",
    date: "01/22/2019 (40w ago)",
    // eslint-disable-next-line global-require
    image: require("../images/noteIcon.svg"),
    type: "payment",
  },
  {
    id: 4,
    title: "hangrydiary submitted ",
    title1: "proposal to collaborate !",
    date: "01/22/2019 (40w ago)",
    // eslint-disable-next-line global-require
    image: require("../images/noteIcon.svg"),
    type: "payment",
  },
  {
    id: 4,
    title: "hangrydiary submitted ",
    title1: "proposal to collaborate !",
    date: "01/22/2019 (40w ago)",
    // eslint-disable-next-line global-require
    image: require("../images/noteIcon.svg"),
    type: "payment",
  },
  {
    id: 4,
    title: "hangrydiary submitted ",
    title1: "proposal to collaborate !",
    date: "01/22/2019 (40w ago)",
    // eslint-disable-next-line global-require
    image: require("../images/dollarIcon.svg"),
    type: "payment",
  },
  {
    id: 4,
    title: "hangrydiary submitted ",
    title1: "proposal to collaborate !",
    date: "01/22/2019 (40w ago)",
    // eslint-disable-next-line global-require
    image: require("../images/noteIcon.svg"),
    type: "payment",
  },
  {
    id: 4,
    title: "hangrydiary submitted ",
    title1: "proposal to collaborate !",
    date: "01/22/2019 (40w ago)",
    // eslint-disable-next-line global-require
    image: require("../images/noteIcon.svg"),
    type: "payment",
  },
];

const innerDataList00 = [
  { id: 15, imageUrl: imageUrls[0], title: "HelloFresh", time: "5w" },
  { id: 16, imageUrl: imageUrls[1], title: "Postmark", time: "13w" },
  { id: 17, imageUrl: imageUrls[2], title: "Dyson Us", time: "3w" },
  { id: 18, imageUrl: imageUrls[3], title: "Samsung Home", time: "3w" },
  { id: 19, imageUrl: imageUrls[4], title: "Dyson Uk", time: "6w" },
  { id: 20, imageUrl: imageUrls[5], title: "Oster", time: "7w" },
  { id: 21, imageUrl: imageUrls[6], title: "Crock-Pot", time: "9w" },
  { id: 22, imageUrl: imageUrls[7], title: "West Elm", time: "3w" },
  { id: 23, imageUrl: imageUrls[8], title: "FoodSaver", time: "3w" },
  { id: 24, imageUrl: imageUrls[9], title: "Splenda", time: "3w" },
  { id: 15, imageUrl: imageUrls[0], title: "HelloFresh", time: "5w" },
  { id: 16, imageUrl: imageUrls[1], title: "Postmark", time: "13w" },
  { id: 17, imageUrl: imageUrls[2], title: "Dyson Us", time: "3w" },
  { id: 18, imageUrl: imageUrls[3], title: "Samsung Home", time: "3w" },
  { id: 19, imageUrl: imageUrls[4], title: "Dyson Uk", time: "6w" },
  { id: 20, imageUrl: imageUrls[5], title: "Oster", time: "7w" },
  { id: 21, imageUrl: imageUrls[6], title: "Crock-Pot", time: "9w" },
  { id: 22, imageUrl: imageUrls[7], title: "West Elm", time: "3w" },
  { id: 23, imageUrl: imageUrls[8], title: "FoodSaver", time: "3w" },
  { id: 24, imageUrl: imageUrls[9], title: "Splenda", time: "3w" },
];
const innerDataList0 = [
  {
    id: 12,
    title: "New Proposals",
    count: 3,
    nestedInnerDataList: innerDataList00,
  },
];

const innerDataList1 = [
  { id: 3, title: "Discovery", count: 3, isBullet: true },
  { id: 4, title: "Negotiation", count: 4, isBullet: true },
  { id: 5, title: "Product Selection", count: 5, isBullet: true },
  { id: 6, title: "Shipment Pending", count: 6, isBullet: true },
  { id: 7, title: "Product in Transit", count: 7, isBullet: true },
  { id: 8, title: "Create Content", count: 8, isBullet: true },
  { id: 9, title: "Review Content", count: 9, isBullet: true },
  { id: 10, title: "Payment", count: 10, isBullet: true },
  { id: 11, title: "Write Review", count: 11, isBullet: true },
];

export const DRAWER_TABS_LIST = [
  { id: 0, title: "Opportunities", innerDataList: innerDataList0, count: 0 },
  { id: 1, title: "In Progress", innerDataList: innerDataList1, count: 1 },
  { id: 2, title: "Complete", count: 2 },
];

export const REVIEW_DATA_LIST = [
  {
    id: 1,
    title: "Collab Terms",
    subtitle: "You have agreed to collab terms!",
    // eslint-disable-next-line global-require
    image: require("../images/yellowCircleTick.svg"),
  },
  {
    id: 2,
    title: "Product Selection & Tracking",
    subtitle: "Product shipment skipped",
    // eslint-disable-next-line global-require
    image: require("../images/yellowCircleTick.svg"),
  },
  {
    id: 3,
    title: "Submit Content & Set Live",
    subtitle: "All content requirements are complete!",
    // eslint-disable-next-line global-require
    // eslint-disable-next-line global-require
    image: require("../images/yellowCircleTick.svg"),
  },
  {
    id: 4,
    title: "Posts Summary",
    subtitle: "All content has been delivered",
    // eslint-disable-next-line global-require
    image: require("../images/yellowCircleTick.svg"),
  },
  {
    id: 5,
    title: "Payments",
    subtitle: "Payment has been send",
    // eslint-disable-next-line global-require
    image: require("../images/yellowCircleTick.svg"),
  },
];

export const lstrings = new LocalizedStrings({
  en: {
    postdate: "Post Date",

    buypremium:
      "To view more Influencer profiles, please join our membership program. Details please contact support@popared.com or +852 6563 1035",
    activateaccountmsg:
      "Please activate your account by verifying in your email address, if you haven’t received it, we can resend the activation email by clicking",
    here: "here",
    afterhere: "",
    type: "Type",

    //creatorspecific
    creatorcampaigns: "Campaigns",
    creatorpayment: "Payment",
    creatorperiodlabel: "Your Campaign Period",
    creatordescribelabel: "What you are looking for/Any brief",

    brandformatlistlabel: "Options",
    onlynumberallowed: "Input field limit to number only",

    campaignstate: {
      S: "Bid Submitted",
      L: "Pending Offer",
      M: "Pending Accept",
      T: "Pending Ship",
      R: "Shipped",
      B: "Pending Delivery",
      A: "Pending Approve",
      D: "Pending Payment Detail",
      P: "Pending Settlement",
      E: "Pending Review",
      C: "Completed",
      I: "Invited",
      F: "Rejected",
      W: "Withdrew",
      CPP: "Completed (Pending settlement)",
      notalldone: "Not all tasks have been done",
    },

    countryregion: "Country/Region",
    selecttag: "Select Tag",
    select: "Select",
    searchtags: "Search Tags",
    socialnetworks: "Social Networks",
    chart: "Influencers Top 100",
    succeeded: "succeeded",
    print: "Print",
    export: "Export",

    media_type: "Media type",
    carousel_album_engagement: "Engagement",
    carousel_album_impressions: "Impressions",
    carousel_album_reach: "Reach",
    saved: "Saved",
    video_views: "Video views",
    engagement: "Engagement",
    impressions: "Impressions",
    reach: "Reach",
    latestpostinsight: "Latest post insight:",

    allcategories: {
      AnimalPets: "Animal/Pets",
      ArtDesign: "Art/Design",
      Beauty: "Beauty",
      BusinessEntrepreneurship: "Business/Entrepreneurship",
      Entertainment: "Entertainment",
      FamilyParenting: "Family/Parenting",
      Fashion: "Fashion",
      Food: "Food",
      Gaming: "Gaming",
      HealthFitness: "Health/Fitness",
      HobbyInterest: "Hobby/Interest",
      MusicDance: "Music/Dance",
      RelationshipLove: "Relationship/Love",
      Travel: "Travel",
      TechnologyScience: "Technology/Science",
      Others: "Others",
    },

    grid: "Grid",
    list: "List",

    //billing
    billing: "Billing",
    addfunds: "Add Funds",
    balance: "Balance",
    amount: "Amount",
    description: "Description",
    transactionnumber: "Transaction Number",
    accountbalance: "Account Balance",
    campaignbalance: "Campaign Balance",
    download: "Download",
    addedfundsuccess: "Fund added succssfully",
    billingInformation: "BILLING INFORMATION",
    currentSubscribe: "Current Subscription",
    duration_m: "MO",
    duration_y: "YR",
    duration_ms: "MO",
    duration_ys: "YR",
    billingStarts: "Billing Starts",
    prevdate: "Previous Billing Date",
    activated: "activated",
    cancelledsubscriptionrenewal: "cancelled subscription renewal",
    billingdatedesc:
      "Your subscription will renew automatically unless cancelled by ",
    billingdatedesc_cnlast: "",
    billingdatedesc_cancel: "Your subscription will end on",
    billingdatedesc_cnlast_cancel:
      ", thereafter you will continue to enjoy our free trial functions, we hope you decide to upgrade again!",
    change: "CHANGE",
    cancel_C: "CANCEL",
    cancelbilltitle: "Are you sure you want to unsubscribe?",
    billingTotal: "Total",
    subscribeAgain: "Subscribe Again",
    pay: "Pay",
    paydesc: "Additional 4% handling fee will be charged every top up",
    cancelsubscription:
      "Subscription cancellation request is received and currently in process, the status will be updated in your account once completed.",
    payempty: "Please input the amount",

    //Header
    logout: "Logout",
    campaigns: "Campaigns",
    findyourcreators: "Influencers Search",
    recommended: "Influencers Top 100",
    risingstar: "Rising Star",
    popularposts: "Popular Posts",
    favourites: "My List",
    watchlist: "Keywords Search",
    upgradeyourplan: "Upgrade Your Plan",
    campaign: "Campaign",
    help: "Help",
    settings: "Settings",
    home: "Home",

    messages: "Messages",
    results: "Results",
    blog: "Blog",

    yourviewhistory: "Your view history",
    recommendedforyou: "Recommended for you",
    goodmorning: "Good Morning,",
    goodafternoon: "Good Afternoon,",
    goodevening: "Good Evening,",

    //Find Your Creator
    categories: "Categories",
    genders: "Genders",
    platform: "Platform",
    location: "Location",
    followers: "Followers",
    likeperPost: "Like Per Post",
    likes: "Likes",
    applysearchandfilter: "Apply Search & Filters",
    creatorsfound: "influencers found",
    sortby: "Sort by",
    noresultfound: "No result found",
    searchcreatorname: "Search influencer",
    grade: "Grade",
    engagementrate: "Enagement Rate",
    showmore: "Show More",
    all: "All",
    xhs: "xiaohongshu",
    hongkong: "Hong Kong",
    taiwan: "Taiwan",
    china: "China",
    usa: "United States",
    notspecific: "Not Specific",
    male: "Male",
    female: "Female",

    //Recommended
    name: "Name",
    platforms: "Platforms",
    totalfollowers: "Total Followers (K)",
    averagelikes: "Average Likes",
    averagecomments: "Average Comments",
    averagecollects: "Average Collects",

    comments: "Comments",

    //Watch List
    savedwatchlist: "Saved Watch List",
    hashtag: "Hashtag",
    periodoftime: "Period of time",
    from: "From",
    to: "To",
    applysearch: "Apply Search",
    savetowatchlist: "Save to Watch List",
    bookmarkThis: "Bookmark This",
    wlfind: "",
    postsfound: "posts found",
    pleaseselectdate: "Please Select Date",
    remove: "Remove",
    pleaseenterhashtag: "Please enter Hashtag",
    pleaseenterfromandtodate: "Please enter Both From Date and To Date",
    pleaseentername: "Please enter name",
    watchlistsavedsuccess: "Watch List saved successfully",
    watchlistremovedsuccess: "Watch List removed successfully",
    cancel: "Cancel",
    save: "Save",
    enterwatchlistname: "Enter Watch List Name",
    last90days: "Last 90 Days",
    last365days: "Last 365 Days",
    youmayalsointerest: "Might be of your interset",

    //Upgrade Your Plan
    freetrialsoon:
      "Free trial subscriptions available until May 2021! Additional functions upgrade in progress!",
    feedbacksoon: "Provide feedback and earn a premium subscription discount!",

    //Settings
    accountinfo: "Account Info",
    email: "Email",
    firstname: "First Name",
    pleaseenterfirstname: "Please enter first name",
    lastname: "Last Name",
    pleaseenterlastname: "Please enter last name",
    uploadprofilepicture: "Upload Profile Picture",
    imagemustbeandsoon:
      "image must be in JPG or PNG format and cannot exceed 8MB",
    update: "Update",

    notifications: "Notifications",
    on: "ON",
    off: "OFF",
    bidsubmitted: "Bid Submitted",
    whenbidaresubmitted: "Receive notification when bid are submitted",
    revisionsubmitted: "Revision Submitted",
    whenrevisionsaresubmitted:
      "Receive notification when revisions are submitted",
    messagepostedbycreator: "Message Posted By Influencer",
    whenyourreceivemessageorquestions:
      "Receive notification when your receive message or questions",
    submissioncanceledbycreator: "Submission Canceled By Influencer",
    whenCreatorscanceltheirsubmissions:
      "Receive notification when Influencers cancel their submissions",
    postwentlive: "Post Went Live",
    postgotliveonsocialnetwork:
      "Receive notification post got live on social network",
    dailyprojectupdate: "Daily Project Update",
    dailysummaryofnewactivityonyourprojects:
      "Receive a daily summary of new activity on your projects(bids,revisions or messages received)",
    reminderwhenyourresponseisoverdue: "Reminder When your Response is Overdue",
    whenyourresponsetoasubmissionisoverdue:
      "Receive reminders when your response to a submission is overdue",

    companydetails: "Company Details",
    brandname: "Brand Name",
    brandAffinity: "Affiliated Brands",
    pleaseentercompanyname: "Please enter company name",
    companyregisteredname: "Company Registered Name",
    pleaseenterlegalname: "Please enter company legal name",
    billingcontactperson: "Billing Contact Person",
    pleaseenterpersonname: "Please enter contact person name",
    phonenumber: "Phone Number",
    pleaseenterphonenumber: "Please enter company phone number",
    address: "Address",
    pleaseentercompanyaddress: "Please enter company address",

    changepassword: "Change Password",
    currentpassword: "Current Password",
    pleaseentercurrentpassword: "Please enter current password",
    newpassword: "New Password",
    pleaseenternewpassword: "Please enter new password",
    confirmnewpassword: "Confirm New Password",
    pleasereenternewpassword: "Please reenter new password",

    updatedsuccessfully: "Updated successfully",
    newpasswordnotmatch:
      "New password and re-enter new password does not match.",
    success: "Success",
    failed: "Failed",

    //Details
    bio: "Bio",
    tags: "Tags",
    back: "Back",
    overallperformance: "Overall Performance",
    followergrowth: "Follower Growth",
    engagements: "Engagements",
    topposts: "Top Posts",
    similarinfluencers: "Similar Influencers",
    totalfollowers: "Total Followers",
    interactionsperpost: "Interactions per Post",
    totallikes: "Total Likes",
    totalposts: "Total Posts",
    totalcomments: "Total Comments",
    tooltiptotalfollowers: "Number of followers of all platforms",
    tooltipinteractionsperpost:
      "Average number of interactions of recent posts from all platforms Interactions include like, comment and collect (applicable to Xiaohungshu)",
    tooltipengagementRate: "Engagement rate of recent posts from all platforms",
    tooltipaverageLikes:
      "Average number of likes of recent posts from all platforms",
    tooltipaverageComments:
      "Average number of comments of recent posts from all platforms",
    months2: "2M",
    months3: "3M",
    months6: "6M",
    months12: "1Y",
    all: "All",

    followersasc: "Followers (ascending)",
    followersdesc: "Followers (descending)",
    gradeasc: "Grade (ascending)",
    gradedesc: "Grade (descending)",
    engegmentrateasc: "Enagement Rate (ascending)",
    engegmentratedesc: "Enagement Rate (descending)",

    // ------ start from masunsell ----------
    keywords: "Keywords",

    formlistcreatets:
      "Please only select tasks per your chosen platform and fill the quantity (if any)",
    selecttaguser: "Please Select Saved List Creataors",

    createcampaign: "Create Campaign",
    campaignfound: "campaigns found",

    confirmdeactivate: "Are you sure to deactivate it?",
    confirmdelete: "Are you sure to delete it?",
    confirmactivate: "Are you sure to activate it?",
    deactivatesuccess: "Join in Transh Success",

    sendmassmessage: "Send Mass Message",
    send: "Send",
    cancel: "Cancel",
    entermassmessage: "Enter Mass Message",
    entermassmessagevalid: "Please Enter Mass Message!",
    massmessage: "Mass Message",

    entereditpublishdatevalid: "Please Select Publish Date!",

    sendsuccess: "Send successfully",
    tablethname1: "Instragram/xiaohongshu\n  No. of Followers (K)",
    tablethname2: "Shipping Address\nPhone number",
    tablethname3: "Tentaive\nPublish Date",
    rank: "Rank",
    rate: "Rate",
    engagementrate: "Engagement Rate",
    categories: "Categories",
    status: "Status",
    shippingstatus: "Shipping Status",
    trackingcode: "Tracking Code",

    viewdetial: "View Detail",
    HKD: "HKD",
    proposed: "Proposed",
    final: "Final",
    addtoshortlist: "Shortlist / To counter-offer quote",
    makefinal: "Make Final",

    changestatustoshipped: "Change Status to Shipped",

    releasevalid: "Please select at least one item",
    delivered: "Delivered",
    release: "Approve & release fund",
    editpublishdate: "Edit Publish Date",
    confirm: "Confirm",
    edit: "Edit",
    enter: "Enter",
    total: "Total",
    total_b: "TOTAL",

    campaigndetails: "Campaign Details",

    titlelabel: "Your Campaign Title",
    titlevalid: "Please input title!",
    periodlabel: "Your Campaign Period",
    periodvalid: "Please input Period!",
    platform: "Platform",
    platformvalid: "Please select platforms!",
    willgetlabel: "What Influencer will get",
    willgetvalid: "Please select will get!",
    willgetlabel2: "What you’ll get (if approved)",
    formatlist: "Format List",
    formatlistlabel: "Select tasks",

    formatlistvalid: "Please select your options",
    describelabel: "What you are looking for/Any brief",
    describelabel2: "What we’re looking for",
    describevalid: "Please input describe",
    uploadfilevalid: "Please upload files!",
    evaleuate: "Approve & release fund",
    example: "Example",
    content: "Content",
    uploadts: "Upload examples and content for Influencers reference",
    uploadts2: "Canidae is looking for content like:",
    createcampaignbtn1:
      "Publish to Marketplace for Influencers to submit proposal only",
    createcampaignbtn2:
      "Send request for proposals to Saved List Creataors only",
    createcampaignbtn3: "Both publish and send request",
    yoursavedlist: "Your Saved List",
    yoursavedlistts:
      "(Check  the  box if you want to send a proposal request to them)",
    creatorssaved: "Influencers Saved",

    back: "Back",
    from: "From",
    to: "To",
    payment: "Payment",
    products: "Products",

    brandrate: "Brand Rate",
    overallexperience: "Overall Experience",
    promptreply: "Prompt reply",
    goodcontent: "Good content",
    goodcommunication: "Good communication",
    review: "Review",

    // -- notice --
    title: "Title",
    sender: "Sender",
    Date: "Date",
    READ: "READ",
    Unread: "Unread",
    Read: "Read",
    readall: "Read All",

    // -- creator
    browsecampaigns: "Browse Campaigns",
    createdate: "Create Date",
    likesyou: "Likes You",
    welcometooopared: "Welcome to Popared",
    welcometoooparedts:
      "Before receiving your first review, you can apply to work with up to 10 campaigns per month that you are not invited to. if you receive positive reviews on our platform(4 or 5 stars), you’ll no longer be limited in how many brands you can collabrate with. Good luck!",
    mycampaigns: "My Campaigns",
    brandsthatlikedyou: "Brands that liked you",
    newthisweek: "New This Week",
    submitleast1item: "Please submit at least 1 item",
    submitcorrectamount: "Please fill in the correct amount",
    inputyouraddress: "Please input your address",
    availablefor: "Available for",
    imnotinterested: "I’m not interested",
    selectaccountprice: "Select Account & Price",
    selectaccountpricets: "Which account(s) would you post on?",
    youraddress: "Your Address",
    // --- creator message
    opportunities: "Opportunities",
    newproposals: "New Offers",
    pendingaccept: "Pending Accept",
    inprogress: "In Progress",
    productintransit: "Product In Transit",
    contentcreation: "Content Creation",
    completed: "Completed",
    withdrew: "Withdrew",
    rejectedwithdrew: "Rejected / Withdrew",
    alldonevalid: "Please fill all task url before click All Done",
    submit: "Submit",
    yoursubmittedlink: "Your submitted link",
    proposalfor: "Proposal for",
    submittedby: "Submitted by",
    iacceptthisoffer: "I accept this offer",
    goodbyebtn: "Unable to reach consense, collaborate next time",
    receivedproduct: "Received product",
    withdrawfromcampaign: "Withdraw from campaign",
    alldone: "All done",
    youwillreceive: "You will receive",

    accountinfotitle: "Please confirm your bank details",
    yourbankdetails: "Your bank details",
    accountfullname: "Account Full Name",
    bankname: "Bank Name",
    bankaccountno: "Bank Account No",
    submitpaymentdetail: "Submit payment detail",
    on: "on",

    searchcampaigntitle: "Search campaign title",
    chooseplatform: "Choose platform",
    score: "Score",

    active: "Active",
    inactive: "Inactive",
    trash: "Trash",
    completed: "Completed",
    evaluate: "Evaluate",
    viewproposal: "View Quotes",
    shortlistedcreator: "Shortlisted Influencers",
    inrrogress: "In Progress",
    productintransit: "Product In Transit",
    contentcreation: "Content Creation",
    completion: "Completion",
    declinedwithdrew: "Declined / Withdrew",
    createyourcampaign: "Create Your Campaign",

    chatsendplaceholder: "Type a message to",
    inputdeliveryurlhere: "Input delivery url here",

    startdate: "Start date",
    enddate: "End date",

    newtag: "New tag",
    inputtag: "Input tag",

    sendproposal: "Send Quotes",
    inputaddresshere: "Input address here",

    upload: "Upload",
    successfulevaluation: "Successful evaluation",

    maxnoofphoto: "Max No. of Photo",
    inputurl: "Please input delivery url",
    confirmwithdraw: "Are you sure to withdraw?",

    endDateValid: "End time should be greater than today",
    clickheretoopen: "Click here to open",

    gotomessagepage: "Go to message page",

    updateyouraccount: "Update Your Profile",

    handle: "INSTAGRAM ID",
    firstname: "Name",
    lastname: "Last Name",
    phone: "Phone no.",
    gender: "Gender",
    country: "Country",
    categorize: "How would you categorize yourself",
    follower: "Number of followers",
    handlevaild: "Please enter your INSTAGRAM ID",
    firstnamevaild: "Please enter your first name",
    lastnamevaild: "Please enter your last name",
    phonevaild: "Please enter your phone",
    gendervaild: "Please selected your gender",
    countryvaild: "Please selected your country",
    ageinvalid: "Please select your age",
    categorizevaild: "Please selected your categorize",
    followervaild: "Please enter your follower",
    uploadyouravatar: "Upload your avatar",
    uploadyouravatarts:
      "image must be in a JPG or PNG format and cannot exceed 8MB",
    howoldareyou: "How old are you?",
    whatisyouroccupation: "What is your occupation?",
    doyouhavekids: "Do you have kids?",
    ifyeshowold: "If yes, how old?",
    willupostaboutyourotherhalf: "Will u post about your other half?",
    yes: "yes",
    no: "no",
    passwordvaild: "Please enter your password",
    newpasswordvaild: "Please enter your new password",
    newpasswordnotmatchvaild: "The passwords you entered do not match",

    describeyourchannels: "Describe Your Channel's (Max. 3)",
    selectthreeatmost: "Select three at most",

    editmyaccount: "Edit My Account",
    currentpassword: "Current password",
    newpassword: "New password",
    confrimnewpassword: "Confirm new password",

    profile: "Profile",
    totalposts: "Total Posts",
    averagecomments: "Average Comments",
    avglikes: "Avg. likes",
    collabhistory: "Collab History",
    accountinfo: "Account Info",
    personal: "Personal",
    channelcategories: "Channel Categories",
    password: "Password",
    about: "About",

    rating: "Rating",
    urlisnotvalid: "The URL is not valid",

    uploadsizevalid: "Upload image cannot be exceed 10MB",

    budget: "Budget Overview",
    timeexplainspecial1: "submitted on",
    timeexplainspecial1_1: "completed  on",
    timeexplainspecial2: "",
    timeexplainspecial3: "",

    activate: "Activate",

    failedtogetfollowers: "Failed to get latest instagram followers count",
    failedtogetmedia: "Failed to get latest instagram media",
    failedtogetengagement: "Failed to get latest instagram media engagement",
    noreviewsyet: "No reviews yet",
    withdraw: "Withdraw",
    link: "Link",
    connectwithsocialmedia: "Connect with Social Media",
    pleaseconnectall:
      "Please connect all your pages with over 3,000 likes or fans to create your Influencer profile.",
    failedtogetfcount:
      "Failed to get latest instagram followers count, Please click update to get latest followers count",
    name1: "Name :",
    nooffollowers: "No. of followers :",
    latestpostengegment: "Latest post engagement :",
    lastupdatedate: "Last update date :",

    budgetModule: {
      budgetcalculator: "Budget Overview",
      confirmedoffers: "Confirmed Quotes",
      nameofferedserviceselected: "Name  Offered  Service Selected",
      amount: "Amount",
      service: "Service",
      shortlistedcreators: "Shortlisted Influencers",
      add: "Add",
      remove: "Remove",
      budgetpool: "Budget Pool",
      budgetamount: "Budget Amount",
      usedamount_totalbudget: "Remaining Budget",
      total: "Total",
    },

    subscriptionSuccess: " Thanks you for your subscription",
    up: {
      title: "Select Your Plan",
      desc1: "We have free trial and various plans for you.",
      desc2: "Pay monthly, or yearly.",
      desc3: "No pressure. Cancel your subscription anytime.",
      trial: "Trial",
      growth: "Growth",
      boost: "Boost",
      together: "Together",

      free: "Free",
      mo: "MO",
      month: "month",
      ms_mo: "when paying yearly",
      customized: "Customized",
      t_mplanforu: "Tailor-made plan for you",
      t_mplanforu_en: "Customized",

      inuse: "IN SERVICE",
      subscribenow: "SUBSCRIBE NOW",
      reachourteam: "REACH OUR TEAM",

      cardli1: "Unlimited Campaigns",
      cardli2: "Unlimited Influencer Matches",
      cardli3: "Discover Top 100 and Weekly Rising Influencers",
      cardli3_t: "Discover Weekly Rising Influencers",
      cardli4: "All-in-one campaign manager",
      cardli5: "1 Influencer OR Keyword Search per day",
      cardli5_1: "1 Keyword Search per day",
      cardli6: "Unlimited Influencer Searches",
      cardli7: "Unlimited Keyword Searches",
      cardli7_1: "Export Influencer profile analysis",
      cardli8: "Hands off servicing",
      cardli9: "Campaigns/strategies cultivated by our specialist",
      cardli10: "Time-saving communication and reporting",
      cardli11: "Social monitoring insights",
      cardli12: "Paid ad support, multi-campaign management, and more",

      setmeal: "Set Meal",
      annualpayment: "Annual payment",
      ordersummary: "Order summary",
      handlingfee: "Handling Fee",
      notestobuy: "Notes To Buy",
      paytitle: "Your Selected Plan",
      payagent1_f: "Billing starts on ",
      payagent1_a:
        ", and will renew automatically each billing date. If you change your mind, you could cancel your subscription before the upcoming billing date, your plan will cease by the end of current billing period, and payments done will not be refunded.",
      payagent2:
        "By clicking Start Subscription, you’re confirming your purchase of the selected plan, and agreeing to our Terms of Service and Privacy Policy.",
      chooseubillcycle: "Choose Your Billing Cycle",
      billyear: "BILL YEARLY",
      billmonth: "BILL MONTHLY",
      save: "SAVE",
      confirmandproceedtopayment: "CONFIRM AND PROCEED TO PAYMENT",
      selectplan: "SELECTED PLAN",
      changeplan: "Change Plan",
      recommended: "RECOMMENDED",
      plan: ["", "PLAN TOTAL"],
      planDesc: "(Calculated on ratio starting today till next billing date)",
      billStartDate: "BILLING STARTS",
      nextBillDate: "NEXT BILLING DATE",
      billSubtotal: "BALANCE REMAINED from current subscription",
      billTotal: "Amount Payable",
      billTotalDesc: [
        "Billing amount per",
        "will resume original charge once remaining balance is consumed",
      ],
      couponTitle: "Promo Code",
      couponPlaceholder: "enter promotion code here",
      couponButton: ["Enter", "Remove"],
      couponWarning: "Invalid promotion code!",
    },
    subscribenows: {
      ltitle: "THIS FEATURE IS EXCLUSIVE TO SUBSCRIBERS",
      ltitle_last: "YOU’VE EXPLORED OUR PREMIUM FEATURES!",
      ldesc: "Upgrade your plan to unlock",
      rtitle: "UNLOCK MORE PROFESSIONAL FEATURES",
      rtitle1: "Browse all Influencer profile analysis",
      rdesc1: "Easy list view of influencers’ performance in Excel/PDF format",
      rtitle2: "Unlimited Campaigns",
      rdesc2: "Create unlimited number of campaigns on Popared",
      rtitle3: "Unlimited Influencer Matches",
      rdesc3: "Line up with unlimited influencers for your launched campaigns",
      rtitle4: "Discover Top 100 and Weekly Rising Influencers",
      rdesc4:
        "Tap into recent trending Influencers across countries and platform",
      rtitle5: "All-in-one campaign manager",
      rdesc5:
        "Clear view of campaign status; Manage quotes, product shipping, review drafts and collect posted links in one go",
      rtitle6: "Unlimited Influencer Searches",
      rdesc6: "",
      rtitle7: "Unlimited Keyword Searches",
      rdesc7: "",
      maybelater: "maybe later",
    },
  },
  hk: {
    postdate: "發佈日期",
    buypremium:
      "要查看更多網紅個人資料，請加入我們的會員計劃。詳情請聯繫 support@popared.com或+852 6563 1035",
    brandformatlistlabel: "選項",

    activateaccountmsg: "請於驗證電郵中激活你的帳戶, 如果它不在你的收件箱中,請",
    here: "按此",
    afterhere: "重新傳送。",

    //creatorspecific
    creatorcampaigns: "最新活動",
    creatorpayment: "待付款",
    creatorperiodlabel: "活動期限",
    creatordescribelabel: "客戶的創作要求/指引",
    onlynumberallowed: "輸入字段僅為數字",

    campaignstate: {
      S: "已提交報價",
      L: "待報價",
      M: "待接受報價",
      T: "待發貨",
      R: "已發貨",
      B: "待收貨",
      A: "待批核連結網址",
      D: "客戶已批核",
      P: "待付款",
      E: "待評價",
      C: "已完成",
      I: "已邀請",
      F: "已拒絕",
      W: "已退出",
      CPP: "已完成 (待付款)",
      notalldone: "並非所有任務都已完成",
    },

    countryregion: "國家/地區",
    chart: "排行榜",
    succeeded: "成功",
    print: "列印",
    export: "導出",
    socialnetworks: "社交媒體",

    media_type: "媒體類型",
    carousel_album_engagement: "參與度",
    carousel_album_impressions: "曝光次數",
    carousel_album_reach: "觸及次數",
    saved: "已保存",
    video_views: "視頻觀看次數",
    engagement: "參與度",
    impressions: "曝光次數",
    reach: "觸及次數",
    latestpostinsight: "最新發布洞察:",

    allcategories: {
      AnimalPets: "動物",
      ArtDesign: "藝術/設計/文學",
      Beauty: "美容/美妝",
      BusinessEntrepreneurship: "生意/創業",
      Entertainment: "娛樂",
      FamilyParenting: "家庭/教育",
      Fashion: "潮流衣著",
      Food: "美食",
      Gaming: "遊戲",
      HealthFitness: "健康/運動",
      HobbyInterest: "興趣/愛好",
      MusicDance: "音樂/舞蹈",
      RelationshipLove: "關係/戀愛",
      Travel: "旅遊",
      TechnologyScience: "科技/科學",
      Others: "生活日常/其他",
    },

    grid: "網格",
    list: "列表",

    //billing
    billing: "賬戶總覽",
    addfunds: "充值",
    balance: "餘額",
    amount: "金額",
    description: "說明",
    transactionnumber: "交易號碼",
    accountbalance: "帳戶餘額",
    campaignbalance: "行銷活動餘額",
    download: "下載",
    addfundsuccess: "成功充值",
    billingInformation: "賬單資訊",
    currentSubscribe: "你已訂閱的計劃",
    duration_m: "每月",
    duration_y: "每年",
    duration_ms: "月",
    duration_ys: "年",
    billingStarts: "生效日期",
    prevdate: "上一個扣賬日期",
    activated: "已啟用",
    cancelledsubscriptionrenewal: "已取消訂閱",
    billingdatedesc:
      "你的訂閱計劃將於下一個扣賬日期自動扣賬，如欲更改你的選項，請於",
    billingdatedesc_cnlast: "或之前完成指示。",
    billingdatedesc_cancel: "你的訂閱計劃將於",
    billingdatedesc_cnlast_cancel:
      "停止服務，隨後你仍可享受我們免費試用的功能，期待你日後再次訂閱以盡情體驗Popared！",
    change: "變更",
    cancel_C: "取消",
    cancelbilltitle: "你確定取消訂閱嗎?",
    billingTotal: "總結",
    subscribeAgain: "再次訂閱",
    pay: "付款",
    paydesc: "每次交易將收取額外4%手續費",
    cancelsubscription:
      "我們已收到取消訂閱的指示並正在處理中，完成後帳戶內將顯示最新訂閱狀態，請耐心等候。",
    payempty: "請輸入金額",

    home: "首頁",
    yourviewhistory: "曾經瀏覽過的網紅",
    recommendedforyou: "今期推薦的網紅",
    goodmorning: "早晨,",
    goodafternoon: "午安,",
    goodevening: "晚安,",

    followersasc: "粉絲數量 (遞增)",
    followersdesc: "粉絲數量 (遞減)",
    gradeasc: "等級 (遞增)",
    gradedesc: "等級 (遞減)",
    engegmentrateasc: "互動率 (遞增)",
    engegmentratedesc: "互動率 (遞減)",

    //Header
    logout: "登出",
    campaigns: "您的活動",
    findyourcreators: "網紅搜尋",
    recommended: "推介",
    risingstar: "本週排行",
    popularposts: "熱門帖子",
    favourites: "關注名單",
    watchlist: "關鍵字搜尋",
    upgradeyourplan: "訂閲計劃",
    campaign: "你的營銷活動",
    help: "幫助",
    settings: "設定",

    messages: "信息",
    results: "結果",
    blog: "播客",

    //Find Your Creator
    categories: "類別",
    genders: "性別",
    platform: "平台",
    location: "地區",
    followers: "粉絲數量",
    likeperPost: "讚好數量／帖子",
    likes: "讚好",
    applysearchandfilter: "套用／搜尋",
    creatorsfound: "位網紅",
    sortby: "排行",
    noresultfound: "沒有結果",
    searchcreatorname: "搜尋網紅帳戶",
    grade: "等級",
    engagementrate: "互動率",
    showmore: "顯示更多",
    all: "全部",
    xhs: "小紅書",
    hongkong: "香港",
    taiwan: "台灣",
    china: "中國",
    usa: "美國",
    notspecific: "没有提供",
    male: "男",
    female: "女",

    //Recommended
    name: "名字",
    platforms: "平台",
    totalfollowers: "總粉絲數目(K)",
    averagelikes: "平均讚好數",
    averagecomments: "平均留言數",
    averagecollects: "平均收藏數",

    comments: "留言數",

    //Watch List
    savedwatchlist: "儲存你的觀察名單",
    hashtag: "#標籤",
    periodoftime: "時段",
    from: "由",
    to: "至",
    applysearch: "搜尋",
    savetowatchlist: "儲存成觀察名單",
    bookmarkThis: "加入書籤",
    wlfind: "找到",
    postsfound: "個帖子",
    pleaseselectdate: "選擇日期",
    remove: "移除",
    pleaseenterhashtag: "輸入#標籤",
    pleaseenterfromandtodate: "請輸入開始及完結日期",
    pleaseentername: "建立名單名字",
    watchlistsavedsuccess: "成功建立觀察名單",
    watchlistremovedsuccess: "成功移除觀察名單",
    cancel: "取消",
    save: "儲存",
    enterwatchlistname: "輸入觀察名單",
    last90days: "最近 90 天",
    last365days: "最近 365 天",

    //升級你的計劃
    freetrialsoon:
      "免費試用期將於2021年5月完結！請即訂閲我們的付費計劃以解鎖所有平台功能！",
    feedbacksoon: "歡迎回饋意見以獲取折扣",

    //Settings
    accountinfo: "帳戶資料",
    email: "電郵",
    firstname: "名字",
    pleaseenterfirstname: "請輸入你的名字",
    lastname: "姓姓",
    pleaseenterlastname: "請輸入你的姓氏",
    uploadprofilepicture: "上載頭像",
    imagemustbeandsoon: "影像必須以JPG 或PNG 格式上傳，並不能超過8MB。",
    update: "更新",

    notifications: "Notifications",
    on: "ON",
    off: "OFF",
    bidsubmitted: "Bid Submitted",
    whenbidaresubmitted: "Receive notification when bid are submitted",
    revisionsubmitted: "Revision Submitted",
    whenrevisionsaresubmitted:
      "Receive notification when revisions are submitted",
    messagepostedbycreator: "Message Posted By Influencer",
    whenyourreceivemessageorquestions:
      "Receive notification when your receive message or questions",
    submissioncanceledbycreator: "Submission Canceled By Influencer",
    whenCreatorscanceltheirsubmissions:
      "Receive notification when Influencers cancel their submissions",
    postwentlive: "Post Went Live",
    postgotliveonsocialnetwork:
      "Receive notification post got live on social network",
    dailyprojectupdate: "Daily Project Update",
    dailysummaryofnewactivityonyourprojects:
      "Receive a daily summary of new activity on your projects(bids,revisions or messages received)",
    reminderwhenyourresponseisoverdue: "Reminder When your Response is Overdue",
    whenyourresponsetoasubmissionisoverdue:
      "Receive reminders when your response to a submission is overdue",

    companydetails: "公司資料",
    brandname: "品牌名稱",
    brandAffinity: "品牌網絡",
    pleaseentercompanyname: "請輸入你的公司名字",
    companyregisteredname: "公司註冊名字",
    pleaseenterlegalname: "請輸入你公司的註冊名字",
    billingcontactperson: "聯絡人士",
    pleaseenterpersonname: "請輸入聯絡人士姓名",
    phonenumber: "電話號碼",
    pleaseenterphonenumber: "請輸入你的電話號碼",
    address: "地址",
    pleaseentercompanyaddress: "請輸入你的公司地址",

    changepassword: "變更密碼",
    currentpassword: "現有密碼",
    pleaseentercurrentpassword: "請輸入你的現有密碼",
    newpassword: "新密碼",
    pleaseenternewpassword: "請輸入你的新密碼",
    confirmnewpassword: "確認新密碼",
    pleasereenternewpassword: "請重新輸入你的新密碼",

    updatedsuccessfully: "成功更新",
    newpasswordnotmatch: "兩者密碼不相符",
    success: "成功",
    failed: "失敗",

    //Details
    bio: "用戶簡介",
    tags: "標籤",
    back: "返回",
    overallperformance: "整體表現",
    followergrowth: "粉絲增長",
    engagements: "互動",
    topposts: "最火熱帖子",
    similarinfluencers: "類似網紅",
    totalfollowers: "總粉絲數",
    interactionsperpost: "互動/帖子",
    totallikes: "總讚好數",
    totalposts: "總帖子數",
    totalcomments: "總留言數",
    tooltiptotalfollowers: "所有平台的總粉絲人數",
    tooltipinteractionsperpost:
      "所有平台近期帖文的平均互動數 互動數包括：讚好、留言、收藏（適用於小紅書",
    tooltipengagementRate: "所有平台近期帖文的互動率",
    tooltipaverageLikes: "所有平台近期帖文的平均讚好數",
    tooltipaverageComments: "所有平台的近期帖文的平均留言數",
    youmayalsointerest: "你可能感興趣",

    months2: "2個月",
    months3: "3個月",
    months6: "6個月",
    months12: "12個月",
    all: "全部",

    // ------ start from masunsell ----------
    keywords: "關鍵字",

    formlistcreatets: "請依您所選的行銷平台標出需要的行銷形式和數量（如適用）",
    selecttaguser: "請選擇已保存的網紅",

    createcampaign: "創建活動",
    campaignfound: "您的活動",

    confirmdeactivate: "確定要停用它嗎?",
    confirmdelete: "確定要刪除?",
    confirmactivate: "確定要激活它嗎?",
    deactivatesuccess: "成功移到垃圾桶",

    sendmassmessage: "群發消息",
    send: "發送",
    cancel: "取消",
    entermassmessage: "輸入群發消息",
    entermassmessagevalid: "請輸入群發消息!",
    massmessage: "群發消息",

    entereditpublishdatevalid: "請選擇發佈日期!",

    sendsuccess: "發送成功",
    tablethname1: "Instragram/小紅書\n 粉絲數量 (千)",
    tablethname2: "送貨地址\n電話號碼",
    tablethname3: "暫定\n發佈日期",
    rank: "排名",
    rate: "比率",
    engagementrate: "互動率",
    categories: "類別",
    status: "狀態",
    shippingstatus: "寄件狀態",
    trackingcode: "追踪號碼",

    viewdetial: "查看詳情",
    HKD: "港幣",
    proposed: "報價",
    final: "最終",
    addtoshortlist: "加入你的清單/更改報價",
    makefinal: "修改/確認最終報價",

    changestatustoshipped: "將狀態更改為已發貨",

    releasevalid: "請選擇至少一項",
    delivered: "已發佈内容",
    release: "確認已發佈内容無誤並進行付款",
    editpublishdate: "編輯發佈日期",
    confirm: "確認",
    edit: "編輯",
    enter: "輸入",
    total: "總計",
    total_b: "總額",

    campaigndetails: "活動詳細信息",

    title: "標題",
    titlelabel: "您的活動標題",
    titlevalid: "請輸入標題!",
    periodlabel: "您的活動期限",
    periodvalid: "請輸入日期範圍!",
    platform: "行銷平台",
    platformvalid: "請選擇平台!",
    willgetlabel: "您的報酬",
    willgetvalid: "請選擇網紅報酬!",
    willgetlabel2: "您將會得到 (如果獲得批准)",
    formatlist: "格式列表",
    formatlistlabel: "行銷形式",
    formatlistvalid: "請選填您須要的項目!",
    describelabel: "内容創作要求/説明",
    describelabel2: "我們想要做的",
    describevalid: "請輸入內容",
    uploadfilevalid: "請上傳文件!",
    evaleuate: " 評分",
    example: "圖例",
    content: "",
    uploadts: "上傳圖例作網紅參考用",
    uploadts2: "正在尋找類似內容:",
    createcampaignbtn1: "創建活動",
    createcampaignbtn2: "只將活動發佈到已選的網紅",
    createcampaignbtn3: "發佈到活動配對平台和已選的網紅",
    yoursavedlist: "您的網紅列表",
    yoursavedlistts: "(如果要向他們發送報價請求，請選擇該框)",
    creatorssaved: "已保存",

    back: "返回",
    from: "由",
    to: "至",
    payment: "款項",
    products: "產品",

    brandrate: "商戶評價",
    overallexperience: "整體體驗",
    promptreply: "快速回覆",
    goodcontent: "內容良好",
    goodcommunication: "良好溝通",
    review: "評價",

    // -- notice --
    Title: "標題",
    sender: "發出者",
    Date: "日期",
    READ: "已讀",
    Unread: "未讀",
    Read: "讀取",
    readall: "全部讀取",

    // -- creator
    browsecampaigns: "瀏覽活動",
    createdate: "創建日期",
    likesyou: "喜歡你",
    welcometooopared: "歡迎來到Popared",
    welcometoooparedts:
      "在收到您的第一條評論之前，您每月可以向最多10個不被邀請參加的活動提出報價。如果您在我們的平台上獲得好評（4或5星）,您將不會有任何限制。祝你好運!",
    mycampaigns: "我的活動",
    brandsthatlikedyou: "商戶喜歡您",
    newthisweek: "本週新活動",
    submitleast1item: "請提交至少一項",
    submitcorrectamount: "請填寫正確的金額",
    inputyouraddress: "請輸入您的地址",
    availablefor: "適用於",
    imnotinterested: "我不感興趣",
    selectaccountprice: "請選擇帳戶和價格",
    selectaccountpricets: "您會發佈在哪個帳戶?",
    youraddress: "您的地址",
    // --- creator message
    opportunities: "合作機會",
    newproposals: "已報價",
    pendingaccept: "待確認報價",
    inprogress: "進行中",
    productintransit: "產品運輸",
    contentcreation: "內容創建",
    completed: "已完成",
    withdrew: "已退出",
    rejectedwithdrew: "拒絕/退出",
    alldonevalid: "按“全部完成”之前請填寫所有發佈的網址",
    submit: "提交",
    yoursubmittedlink: "您已發佈連結網址",
    proposalfor: "報價給",
    submittedby: "提交人",
    iacceptthisoffer: "我接受此工作",
    goodbyebtn: "無法達成共識，下一次合作",
    receivedproduct: "已收到產品",
    withdrawfromcampaign: "退出活動",
    alldone: "全部完成",
    youwillreceive: "您會收到",

    accountinfotitle: "請輸入你的收款賬戶資料",
    yourbankdetails: "您的銀行信息",
    accountfullname: "帳戶全名",
    bankname: "銀行名稱",
    bankaccountno: "銀行帳號",
    submitpaymentdetail: "提交付款明細",
    on: "於",

    searchcampaigntitle: "搜索活動標題",
    chooseplatform: "選擇平台",
    score: "評分",

    active: "已發佈",
    inactive: "已停用",
    trash: "垃圾箱",
    completed: "已發佈",
    evaluate: "評價",
    viewproposal: "查看報價",
    shortlistedcreator: "待確認報價",
    inrrogress: "進行中",
    productintransit: "產品運輸",
    contentcreation: "內容創作",
    completion: "完成",
    declinedwithdrew: "拒絕 / 撤回",
    createyourcampaign: "創建您的活動",

    chatsendplaceholder: "輸入信息給",
    inputdeliveryurlhere:
      "發佈創作内容前需徵得客戶許可，發佈後在此處輸入連結網址",

    startdate: "開始時間",
    enddate: "結束時間",

    newtag: "新增標籤",
    inputtag: "輸入標籤",

    sendproposal: "提交報價",
    inputaddresshere: "請輸入地址",

    upload: "上傳",
    successfulevaluation: "成功提交評價",

    maxnoofphoto: "最大照片數量",
    inputurl: "請輸入連結網址",
    confirmwithdraw: "確認退出?",

    endDateValid: "結束時間需要大於今天",
    clickheretoopen: "點擊瀏覽",

    gotomessagepage: "前往消息頁",

    updateyouraccount: "更新你的档案",

    handle: "INSTAGRAM ID",
    firstname: "名",
    lastname: "姓",
    phone: "電話號碼",
    gender: "性別",
    country: "國家",
    categorize: "族群",
    follower: "粉絲數目",
    handlevaild: "請輸入Instagram ID",
    firstnamevaild: "請輸入你的名",
    lastnamevaild: "請輸入你的姓",
    phonevaild: "請輸入你的电话号码",
    gendervaild: "請選擇你的性别",
    countryvaild: "請選擇你的國家",
    categorizevaild: "請選擇你的族群",
    followervaild: "請輸入你的粉絲數目",
    ageinvalid: "請選擇你的年齡",
    bio: "簡介",
    uploadyouravatar: "上傳你的頭像",
    uploadyouravatarts: "圖片格式需為JPG或PNG，大小不得超過 8MB",

    howoldareyou: "你今年多少歲？",
    whatisyouroccupation: "你的工作是什麼?",
    doyouhavekids: "你有沒有小孩?",
    ifyeshowold: "如果有, 幾歲?",
    willupostaboutyourotherhalf: "你發帖會否包含另一半?",
    yes: "是",
    no: "否",
    passwordvaild: "請輸入你的密碼",
    newpasswordvaild: "請輸入新密碼",
    newpasswordnotmatchvaild: "請確認兩次新密碼一致",

    describeyourchannels: "形容你的頻道 (最多三個)",
    selectthreeatmost: "最多選三個",

    editmyaccount: "更新你的檔案",
    currentpassword: "現時密碼",
    newpassword: "新密碼",
    confrimnewpassword: "確認新密碼",

    profile: "近期發佈 ",
    totalposts: "總帖子數",
    averagecomments: "平均留言數",
    avglikes: "平均讚好數",
    collabhistory: "活動紀錄",
    accountinfo: "帳戶資料",
    personal: "個人資料",
    channelcategories: "頻道類別",
    password: "密碼",
    about: "關於",

    rating: "評價",
    urlisnotvalid: "這個鏈接無效",

    uploadsizevalid: "上傳圖片不能超過10MB",

    budget: "查看活動預算",
    timeexplainspecial1: "於",
    timeexplainspecial1_1: "於",
    timeexplainspecial2: "提交",
    timeexplainspecial3: "完成",
    activate: "恢復",

    failedtogetfollowers: "未能獲得最新的instagram粉絲數",
    failedtogetmedia: "無法獲取最新的instagram媒體",
    failedtogetengagement: "未能獲得最新的instagram媒體參與率",
    noreviewsyet: "沒有評論",
    withdraw: "提現",
    link: "綁定",
    connectwithsocialmedia: "綁定社交媒體",
    pleaseconnectall:
      "請您綁定超過3,000個讚好或粉絲的專頁與社交媒體，以創建您的個人資料頁。",
    failedtogetfcount:
      "無法獲取最新的instagram粉絲數目，請單擊更新以獲取最新的粉絲數目",
    name1: "名稱 ：",
    nooffollowers: "粉絲數目 ：",
    Latestpostengegment: "最新的參與率 ：",
    lastupdatedate: "最後更新日期 ：",

    budgetModule: {
      budgetcalculator: "活動預算概覽",
      confirmedoffers: "已確認報價",
      nameofferedserviceselected: "服務名稱",
      amount: "金額",
      service: "服務",
      shortlistedcreators: "待確認報價",
      add: "加入",
      remove: "刪除",
      budgetpool: "預算池",
      budgetamount: "預算金額",
      usedamount_totalbudget: "剩餘預算",
      total: "總金額",
    },
    subscriptionSuccess: " 感謝您的訂閱",
    up: {
      title: "選擇您的訂閲計劃",
      desc1: "您可免費試用、隨時升級不同方案",
      desc2: "每月或每年付費，由您選擇",
      desc3: "隨時取消訂閱",
      trial: "試用",
      growth: "增長",
      boost: "企業",
      together: "團隊支援",

      free: "免費",
      mo: "每月",
      month: "月",
      ms_mo: "如選擇年費只需",
      t_mplanforu: "爲你訂製",

      inuse: "正在使用",
      subscribenow: "立即訂閲",
      reachourteam: "聯絡我們",

      cardli1: "無限量創建行銷活動",
      cardli2: "無限量網紅合作數量",
      cardli3: "發掘網紅排行榜及每週熱門網紅",
      cardli3_t: "每週熱門網紅",
      cardli4: "一站式行銷活動管理系統",
      cardli5: "每天一次網紅/關鍵字搜尋",
      cardli5_1: "每天一次關鍵字搜尋",
      cardli6: "無限量網紅搜尋",
      cardli7: "無限量限關鍵字搜尋",
      cardli7_1: "匯出網紅賬戶數據分析",
      cardli8: "度身設計的咨詢服務",
      cardli9: "由Popared團隊打造行銷策略",
      cardli10: "免卻繁複的溝通過程及報告",
      cardli11: "提供所需社群聆聽數據",
      cardli12: "集中管理付費廣告、多項行銷活動的動態，及相關資訊",

      setmeal: "套餐",
      annualpayment: "年付",
      ordersummary: "訂單匯總",
      handlingfee: "手續費",
      notestobuy: "購買須知",
      paytitle: "您的訂閱計劃",
      payagent1_f: "我們會在",
      payagent1_a:
        "開始收費，隨後的每個扣賬日期將自動扣款。您可於下一個扣賬日期前取消訂閱，您的訂閱計劃便會在下一個扣賬日終止， 所有已繳付之費用不設退款 。",
      payagent2:
        "當您按下 「確認並前往付款」，您確認您將購買所選取的訂閱計劃，並已閱讀和理解本站的服務條款及隱私權政策、接受且同意受其約束。",
      chooseubillcycle: "選擇您的扣賬週期",
      billyear: "每年付費",
      billmonth: "每月付費",
      save: "節省",
      confirmandproceedtopayment: "確認並前往付款",
      selectplan: "已選擇的訂閱計劃",
      changeplan: "選擇另一個計劃",
      recommended: "推薦",
      plan: ["訂閱", "計劃"],
      planDesc: "(由訂閱生效日期至下一扣賬日期按比例計算)",
      billStartDate: "訂閱生效日期",
      nextBillDate: "下一個扣賬日期",
      billSubtotal: "現有訂閱餘額",
      billTotal: "應付金額",
      billTotalDesc: ["自動扣賬額將在餘額消耗完畢後恢復原本訂閱價格", ""],
      couponTitle: "促銷代碼",
      couponPlaceholder: "在此處輸入促銷代碼",
      couponButton: ["輸入", "取消"],
      couponWarning: "促銷代碼無效!",
    },
    subscribenows: {
      ltitle: "此為付費功能",
      ltitle_last: "您已完成探索我們的付費功能！",
      ldesc: "請升級你的訂閱計劃",
      rtitle: "解鎖更多專業功能",
      rtitle1: "瀏覽所有網紅帳戶數據分析",
      rdesc1: "輕鬆將網紅數據列表式匯出為Excel/PDF",
      rtitle2: "無限量創建行銷活動",
      rdesc2: "快捷地訂製您的行銷活動",
      rtitle3: "無限量網紅合作數量",
      rdesc3: "隨時獲得網紅推薦、報價和合作，不受配額限制",
      rtitle4: "發掘網紅排行榜及每週熱門網紅",
      rdesc4: "緊貼不同國家和社交平台上的熱門網紅",
      rtitle5: "一站式行銷活動管理系統",
      rdesc5:
        "系統自動更新活動狀態 – 管理報價、寄送產品、批核初稿和收集已發佈帖子連結，省去繁複的步驟",
      rtitle6: "無限量網紅搜尋",
      rtitle7: "無限量限關鍵字搜尋",
      maybelater: "暫不需要",
    },
  },
  cn: {
    activateaccountmsg: "请于验证电邮中激活你的帐户, 如果它不在你的收件箱中,请",
    here: "按此",
    afterhere: "重新传送。",
    //creatorspecific
    creatorcampaigns: "最新活动",
    creatorpayment: "待付款",
    creatorperiodlabel: "活动期限",
    creatordescribelabel: "客户的创作要求/指引",
    brandformatlistlabel: "选项",
    onlynumberallowed: "输入字段仅为数字",

    campaignstate: {
      S: "已提交报价",
      L: "待报价",
      M: "待接受报价",
      T: "待发货",
      R: "已发货",
      B: "待收货",
      A: "待批核连结网址",
      D: "客户已批核",
      P: "待付款",
      E: "待评价",
      C: "已完成",
      I: "已邀请",
      F: "已拒绝",
      W: "已退出",
      CPP: "已完成 (待付款)",
      notalldone: "并非所有任务都已完成",
    },

    postdate: "发布日期",
    countryregion: "国家/地区",
    chart: "排行榜",
    succeeded: "成功",
    socialnetworks: "社交媒体",
    print: "打印",
    export: "导出",
    buypremium:
      "要查看更多网红个人资料，请加入我们的会员计划。详情请联系 support@popared.com或+852 6563 1035",

    media_type: "媒体类型",
    carousel_album_engagement: "参与度",
    carousel_album_impressions: "曝光次数",
    carousel_album_reach: "触及次数",
    saved: "已保存",
    video_views: "视频观看次数",
    engagement: "参与度",
    impressions: "曝光次数",
    reach: "触及次数",
    latestpostinsight: "最新发布洞察:",

    allcategories: {
      AnimalPets: "动物",
      ArtDesign: "艺术/设计/文学",
      Beauty: "美容/美妆",
      BusinessEntrepreneurship: "生意/创业",
      Entertainment: "娱乐",
      FamilyParenting: "家庭/教育",
      Fashion: "潮流衣着",
      Food: "美食",
      Gaming: "游戏",
      HealthFitness: "健康/运动",
      HobbyInterest: "兴趣/爱好",
      MusicDance: "音乐/舞蹈",
      RelationshipLove: "关系/恋爱",
      Travel: "旅游",
      TechnologyScience: "科技/科学",
      Others: "生活日常/其他",
    },

    grid: "网格",
    list: "列表",

    //billing
    billing: "账户总览",
    addfunds: "充值",
    balance: "余额",
    amount: "金额",
    description: "说明",
    transactionnumber: "交易号码",
    accountbalance: "帐户余额",
    campaignbalance: "行销活动余额",
    download: "下载",
    addfundsuccess: "成功充值",
    billingInformation: "账单资讯",
    currentSubscribe: "你已订阅的计划",
    duration_m: "每月",
    duration_y: "每年",
    duration_ms: "月",
    duration_ys: "年",
    billingStarts: "生效日期",
    prevdate: "上一个扣账日期",
    activated: "已启用",
    cancelledsubscriptionrenewal: "已取消订阅",
    billingdatedesc:
      "你的订阅计划将于下一个扣账日期自动扣账，如欲更改你的选项，请于",
    billingdatedesc_cnlast: "或之前完成指示。",
    billingdatedesc_cancel: "你的订阅计划将于",
    billingdatedesc_cnlast_cancel:
      "停止服务，随后你仍可享受我们免费试用的功能，期待你日后再次订阅以尽情体验Popared！",
    change: "变更",
    cancel_C: "取消",
    cancelbilltitle: "你确定取消订阅吗?",
    billingTotal: "总结",
    subscribeAgain: "再次订阅",
    pay: "付款",
    paydesc: "每次交易将收取额外4%手续费",
    cancelsubscription:
      "我们已收到取消订阅的指示并正在处理中，完成后帐户内将显示最新订阅状态，请耐心等候。",
    payempty: "请输入金额",

    home: "首页",
    yourviewhistory: "曾经浏览过的网红",
    recommendedforyou: "今期推荐的网红",
    goodmorning: "早晨,",
    goodafternoon: "午安,",
    goodevening: "晚安,",

    followersasc: "粉丝数量 (递增)",
    followersdesc: "粉丝数量 (递减)",
    gradeasc: "等级 (递增)",
    gradedesc: "等级 (递减)",
    engegmentrateasc: "互动率 (递增)",
    engegmentratedesc: "互动率 (递减)",

    //Header
    logout: "登出",
    campaigns: "您的活动",
    findyourcreators: "网红搜索",
    recommended: "推介",
    risingstar: "本周排行",
    popularposts: "热门帖子",
    favourites: "关注名单",
    watchlist: "关键字搜寻",
    upgradeyourplan: "订阅计划",
    campaign: "你的营销活动",
    help: "帮助",
    settings: "设定",

    messages: "信息",
    results: "结果",
    blog: "播客",

    //Find Your Creator
    categories: "类别",
    genders: "性别",
    platform: "平台",
    location: "地区",
    followers: "粉丝数量",
    likeperPost: "赞好数量／帖子",
    likes: "赞好",
    applysearchandfilter: "套用／搜寻",
    creatorsfound: "位网红",
    sortby: "排行",
    noresultfound: "没有结果",
    searchcreatorname: "搜寻网红帐户",
    grade: "等级",
    engagementrate: "互动率",
    showmore: "显示更多",
    all: "全部",
    xhs: "小红书",
    hongkong: "香港",
    taiwan: "台湾",
    china: "中国",
    usa: "美国",
    notspecific: "没有提供",
    male: "男",
    female: "女",

    //Recommended
    name: "名字",
    platforms: "平台",
    totalfollowers: "总粉丝数目(K)",
    averagelikes: "平均赞好数",
    averagecomments: "平均留言数",
    averagecollects: "平均收藏数",

    comments: "留言数",

    //Watch List
    savedwatchlist: "储存你的观察名单",
    hashtag: "#标签",
    periodoftime: "时段",
    from: "由",
    to: "至",
    applysearch: "搜寻",
    savetowatchlist: "储存成观察名单",
    bookmarkThis: "加入书签",
    wlfind: "找到",
    postsfound: "个帖子",
    pleaseselectdate: "选择日期",
    remove: "移除",
    pleaseenterhashtag: "输入#标签",
    pleaseenterfromandtodate: "请输入开始及完结日期",
    pleaseentername: "建立名单名字",
    watchlistsavedsuccess: "成功建立观察名单",
    watchlistremovedsuccess: "成功移除观察名单",
    enterwatchlistname: "输入观察名单",
    last90days: "最近 90 天",
    last365days: "最近 365 天",
    youmayalsointerest: "你可能感兴趣",

    //升级你的计划
    freetrialsoon:
      "免费试用期将于2021年5月完结！请即订阅我们的付费计划以解锁所有平台功能！",
    feedbacksoon: "欢迎回馈意见以获取折扣",

    //Settings
    accountinfo: "帐户资料",
    email: "电邮",
    firstname: "名字:",
    pleaseenterfirstname: "请输入你的名字",
    lastname: "姓姓:",
    pleaseenterlastname: "请输入你的姓氏",
    uploadprofilepicture: "上载头像",
    imagemustbeandsoon: "影像必须以JPG 或PNG 格式上传，并不能超过8MB。 ",
    update: "更新",

    notifications: "Notifications",
    on: "ON",
    off: "OFF",
    bidsubmitted: "Bid Submitted",
    whenbidaresubmitted: "Receive notification when bid are submitted",
    revisionsubmitted: "Revision Submitted",
    whenrevisionsaresubmitted:
      "Receive notification when revisions are submitted",
    messagepostedbycreator: "Message Posted By Influencer",
    whenyourreceivemessageorquestions:
      "Receive notification when your receive message or questions",
    submissioncanceledbycreator: "Submission Canceled By Influencer",
    whenCreatorscanceltheirsubmissions:
      "Receive notification when Influencers cancel their submissions",
    postwentlive: "Post Went Live",
    postgotliveonsocialnetwork:
      "Receive notification post got live on social network",
    dailyprojectupdate: "Daily Project Update",
    dailysummaryofnewactivityonyourprojects:
      "Receive a daily summary of new activity on your projects(bids,revisions or messages received)",
    reminderwhenyourresponseisoverdue: "Reminder When your Response is Overdue",
    whenyourresponsetoasubmissionisoverdue:
      "Receive reminders when your response to a submission is overdue",

    companydetails: "公司资料",
    brandname: "品牌名称",
    brandAffinity: "品牌网络",
    pleaseentercompanyname: "请输入你的公司名字",
    companyregisteredname: "公司注册名字",
    pleaseenterlegalname: "请输入你公司的注册名字",
    billingcontactperson: "联络人士",
    pleaseenterpersonname: "请输入联络人士姓名",
    phonenumber: "电话号码",
    pleaseenterphonenumber: "请输入你的电话号码",
    address: "地址",
    pleaseentercompanyaddress: "请输入你的公司地址",

    changepassword: "变更密码",
    currentpassword: "现有密码",
    pleaseentercurrentpassword: "请输入你的现有密码",
    newpassword: "新密码",
    pleaseenternewpassword: "请输入你的新密码",
    confirmnewpassword: "确认新密码",
    pleasereenternewpassword: "请重新输入你的新密码",

    updatedsuccessfully: "成功更新",
    newpasswordnotmatch: "两者密码不相符",
    success: "成功",
    failed: "失败",

    //Details
    bio: "用户简介",
    tags: "标签",
    back: "返回",
    overallperformance: "整体表现",
    followergrowth: "粉丝增长",
    engagements: "互动",
    topposts: "最火热帖子",
    similarinfluencers: "类似网红",
    totalfollowers: "总粉丝数",
    interactionsperpost: "互动/帖子",
    totallikes: "总赞好数",
    totalposts: "总帖子数",
    totalcomments: "总留言数",
    tooltiptotalfollowers: "所有平台的總粉絲人數",
    tooltipinteractionsperpost:
      "所有平台近期帖文的平均互動數 互動數包括：讚好、留言、收藏（適用於小紅書",
    tooltipengagementRate: "所有平台近期帖文的互動率",
    tooltipaverageLikes: "所有平台近期帖文的平均讚好數",
    tooltipaverageComments: "所有平台的近期帖文的平均留言數",

    months2: "2个月",
    months3: "3个月",
    months6: "6个月",
    months12: "12个月",
    all: "全部",

    // ------ start from masunsell ----------
    keywords: "关键字",

    formlistcreatets: "请依您所选的行销平台标出需要的行销形式和数量（如适用）",
    selecttaguser: "请选择已保存的网红",

    createcampaign: "创建活动",
    campaignfound: "您的活动",

    confirmdeactivate: "确定要停用它吗?",
    confirmdelete: "确定要删除?",
    confirmactivate: "确定要激活它吗?",
    deactivatesuccess: "成功移到垃圾桶",

    sendmassmessage: "群发消息",
    send: "发送",
    cancel: "取消",
    entermassmessage: "输入群发消息",
    entermassmessagevalid: "请输入群发消息!",
    massmessage: "群发消息",

    entereditpublishdatevalid: "请选择发布日期!",

    sendsuccess: "发送成功",
    tablethname1: "Instragram/小红书\n 粉丝数量 (千)",
    tablethname2: "送货地址\n电话号码",
    tablethname3: "临时\n发布日期",
    rank: "排名",
    rate: "比率",
    engagementrate: "互动率",
    categories: "类别",
    status: "状态",
    shippingstatus: "寄件状态",
    trackingcode: "追踪号码",

    viewdetial: "查看明细",
    HKD: "港币",
    proposed: "报价",
    final: "最终",
    addtoshortlist: "加入你的清单/更改报价",
    makefinal: "修改/确认最终报价",

    changestatustoshipped: "把状态更改为已发货",

    releasevalid: "请选择至少一项",
    delivered: "已发布内容",
    release: "确认已发布内容无误并进行付款",
    editpublishdate: "编辑发布日期",
    confirm: "确认",
    edit: "修改",
    enter: "输入",
    total: "总计",
    total_b: "总额",

    campaigndetails: "活动详细信息",

    title: "标题",
    titlelabel: "您的活动标题",
    titlevalid: "请输入标题!",
    periodlabel: "您的活动期限",
    periodvalid: "请输入日期范围!",
    platform: "行销平台",
    platformvalid: "请选择平台!",
    willgetlabel: "您的报酬",
    willgetvalid: "请选择网红报酬!",
    willgetlabel2: "您将会得到 (如果获得批准)",
    formatlist: "格式列表",
    formatlistlabel: "行销形式",
    formatlistvalid: "请选填您须要的项目!",
    describelabel: "内容创建请求/说明",
    describelabel2: "我们想要做的",
    describevalid: "请输入内容",
    uploadfilevalid: "请上传文件!",
    evaleuate: "评分",
    example: "图例",
    content: "",
    uploadts: "上传图例作网红参考用",
    uploadts2: "正在寻找类似内容:",
    createcampaignbtn1: "创建活动",
    createcampaignbtn2: "只将活动发布到已选的网红",
    createcampaignbtn3: "发布到活动配对平台和已选的网红",
    save: "保存",
    cancel: "取消",
    yoursavedlist: "您的网红列表",
    yoursavedlistts: "(如果要向他们发送报价请求，请选择该框)",
    creatorssaved: "已保存",

    back: "返回",
    from: "由",
    to: "至",
    payment: "款项",
    products: "产品",

    brandrate: "商户评价",
    overallexperience: "整体体验",
    promptreply: "快速回覆",
    goodcontent: "内容良好",
    goodcommunication: "良好沟通",
    review: "评价",

    // -- notice --
    Title: "标题",
    sender: "发出者",
    Date: "日期",
    READ: "已读",
    Unread: "未读",
    Read: "读取",
    readall: "全部读取",
    // -- creator
    browsecampaigns: "浏览活动",
    createdate: "创建日期",
    likesyou: "喜欢你",
    welcometooopared: "欢迎来到Popared",
    welcometoooparedts:
      "在收到您的第一条评论之前，您每月可以向最多10个不被邀请参加的活动提出报价。如果您在我们的平台上获得好评（4或5星）,您将不会有任何限制。祝你好运!",
    mycampaigns: "我的活动",
    brandsthatlikedyou: "商户喜欢您",
    newthisweek: "本周新活动",
    submitleast1item: "请提交至少一项",
    submitcorrectamount: "请填写正确的金额",
    inputyouraddress: "请输入您的地址",
    availablefor: "适用于",
    imnotinterested: "我不感兴趣",
    selectaccountprice: "请选择帐户和价格",
    selectaccountpricets: "您会发布在哪个帐户?",
    youraddress: "您的地址",
    // --- creator message
    opportunities: "合作机会",
    newproposals: "已报价",
    pendingaccept: "待确认报价",
    inprogress: "进行中",
    productintransit: "产品运输中",
    contentcreation: "内容创建中",
    completed: "已发布",
    withdrew: "已退出",
    rejectedwithdrew: "拒绝/退出",
    alldonevalid: "按“全部完成”之前请填写所有发布的网址",
    submit: "提交",
    yoursubmittedlink: "您已发布连结网址",
    proposalfor: "报价给",
    submittedby: "提交人",
    iacceptthisoffer: "我接受此工作",
    goodbyebtn: "无法达成共识，下一次合作",
    receivedproduct: "已收到产品",
    withdrawfromcampaign: "退出活动",
    alldone: "全部完成",
    youwillreceive: "您会收到",

    accountinfotitle: "请输入你的收款账户资料",
    yourbankdetails: "您的银行信息",
    accountfullname: "帐户全名",
    bankname: "银行名称",
    bankaccountno: "银行帐号",
    submitpaymentdetail: "提交付款明细",
    on: "于",

    searchcampaigntitle: "搜索活动标题",
    chooseplatform: "选择平台",
    score: "评分",

    active: "已发布",
    inactive: "已停用",
    trash: "垃圾箱",
    completed: "已完成",
    evaluate: "评价",
    viewproposal: "查看报价",
    shortlistedcreator: "入围",
    inrrogress: "进行中",
    productintransit: "产品运输中",
    contentcreation: "内容创建中",
    completion: "完成",
    declinedwithdrew: "拒绝 / 撤回",
    createyourcampaign: "创建您的活动",

    chatsendplaceholder: "输入信息给",
    inputdeliveryurlhere:
      "发布创作内容前需征得客户许可，发布后在此处输入连结网址",

    startdate: "开始时间",
    enddate: "结束时间",

    newtag: "新增标签",
    inputtag: "输入标签",

    sendproposal: "提交报价",
    inputaddresshere: "请输入地址",

    upload: "上传",
    successfulevaluation: "打分提交成功",

    maxnoofphoto: "最大照片数量",
    inputurl: "请输入连结网址",
    confirmwithdraw: "确认退出?",

    endDateValid: "结束时间需要大于今天",
    clickheretoopen: "点击浏览",

    gotomessagepage: "前往消息页",

    updateyouraccount: "更新你的档案",

    handle: "INSTAGRAM ID",
    firstname: "名",
    lastname: "姓",
    phone: "电话号码",
    gender: "性别",
    country: "国家",
    categorize: "族群",
    follower: "粉丝数目",
    handlevaild: "请输入Instagram ID",
    firstnamevaild: "请输入你的名",
    lastnamevaild: "请输入你的姓",
    phonevaild: "请输入你的电话号码",
    gendervaild: "请选择你的性别",
    countryvaild: "请选择你的国家",
    categorizevaild: "请选择你的族群",
    followervaild: "请输入你的粉丝数目",
    ageinvalid: "请选择你的年龄",
    bio: "简介",
    uploadyouravatar: "上传你的头像",
    uploadyouravatarts: "图片格式需为JPG或PNG，大小不得超过 8MB",

    howoldareyou: "你今年多少岁？",
    whatisyouroccupation: "你的工作是什么?",
    doyouhavekids: "你有没有小孩?",
    ifyeshowold: "如果有, 几岁?",
    willupostaboutyourotherhalf: "你发贴会否包含另一半?",
    yes: "是",
    no: "否",
    passwordvaild: "请输入你的密码",
    newpasswordvaild: "请输入新密码",
    newpasswordnotmatchvaild: "请确认两次新密码一致",

    describeyourchannels: "形容你的频道 (最多三个)",
    selectthreeatmost: "最多选三个",

    editmyaccount: "更新你的档案",
    currentpassword: "现时密码",
    newpassword: "新密码",
    confrimnewpassword: "确认新密码",

    profile: "近期发布",
    totalposts: "总帖子数",
    averagecomments: "平均留言数",
    avglikes: "平均点赞数",
    collabhistory: "活动纪录",
    accountinfo: "帐户资料",
    personal: "个人资料",
    channelcategories: "频道类别",
    password: "密码",
    about: "关于",

    rating: "评价",
    urlisnotvalid: "这个链接无效",

    uploadsizevalid: "上传图片不能超过10MB",

    budget: "查看活动预算",
    timeexplainspecial1: "于",
    timeexplainspecial1_1: "于",
    timeexplainspecial2: "提交",
    timeexplainspecial3: "完成",

    activate: "激活",

    failedtogetfollowers: "未能获得最新的instagram粉丝数",
    failedtogetmedia: "无法获取最新的instagram媒体",
    failedtogetengagement: "未能获得最新的instagram媒体参与率",
    noreviewsyet: "没有评论",
    withdraw: "提现",
    link: "绑定",
    connectwithsocialmedia: "绑定社交媒体",
    pleaseconnectall:
      "请您绑定超过3,000个赞好或粉丝的专页与社交媒体，以创建您的个人资料页。 ",
    failedtogetfcount:
      "无法获取最新的instagram粉丝数目，请单击更新以获取最新的粉丝数目",
    name1: "名称 :",
    nooffollowers: "粉丝数目 :",
    Latestpostengegment: "最新的参与率 :",
    lastupdatedate: "最后更新日期 :",

    budgetModule: {
      budgetcalculator: "活动预算概览",
      confirmedoffers: "已确认报价",
      nameofferedserviceselected: "服务名称",
      amount: "金额",
      service: "服务",
      shortlistedcreators: "候选清单",
      add: "加入",
      remove: "刪除",
      budgetpool: "预算池",
      budgetamount: "预算金额",
      usedamount_totalbudget: "剩余预算",
      total: "总金额",
    },

    subscriptionSuccess: " 感谢您的订阅",
    up: {
      title: "请选择您的订阅计划",
      desc1: "您可免费试用、随时升级不同方案",
      desc2: "每月或每年付费，由您选择",
      desc3: "随时取消订阅",
      trial: "试用",
      growth: "增长",
      boost: "企业",
      together: "团队支援",

      free: "免费",
      mo: "每月",
      month: "月",
      ms_mo: "如选择年费只需",
      t_mplanforu: "为你定制",

      inuse: "正在使用",
      subscribenow: "立即订阅",
      reachourteam: "联络我们",

      cardli1: "无限量创建行销活动",
      cardli2: "无限量网红合作数量",
      cardli3: "发掘网红排行榜及每周热门网红",
      cardli3_t: "每周热门网红",
      cardli4: "一站式行销活动管理系统",
      cardli5: "每天一次网红/关键字搜寻",
      cardli5_1: "每天一次关键字搜寻",
      cardli6: "无限量网红搜寻",
      cardli7: "无限量关键字搜寻",
      cardli7_1: "汇出网红账户数据分析",
      cardli8: "度身设计的咨询服务",
      cardli9: "由Popared团队打造行销策略",
      cardli10: "免却复杂的沟通过程及报告",
      cardli11: "提供所需社群聆听数据",
      cardli12: "集中管理付费广告、多项行销活动的动态，及相关资讯",

      setmeal: "套餐",
      annualpayment: "年付",
      ordersummary: "订单汇总",
      handlingfee: "手续费",
      notestobuy: "购买须知",
      paytitle: "您的订阅计划",
      payagent1_f: "我们会在",
      payagent1_a:
        "开始收费，随后的每个扣帐日期将自动扣款。您可于下一个扣帐日期前取消订阅，您的订阅计划便会在下一个扣帐日终止，所有已缴付之费用不设退款。",
      payagent2:
        "当您按下「确认并前往付款」，您确认您将购买所提取的订阅计划，并已阅读和理解本站的服务条款及隐私权政策、接受且同意受其约束。",
      chooseubillcycle: "选择您的扣帐周期",
      billyear: "每年付费",
      billmonth: "每月付费",
      save: "节省",
      confirmandproceedtopayment: "确认并前往付款",
      selectplan: "已选择的订阅计划",
      changeplan: "选择另一个计划",
      recommended: "推荐",
      plan: ["订阅", "计划"],
      planDesc: "(由订阅生效日期至下一扣账日期按比例计算)",
      billStartDate: "订阅生效日期",
      nextBillDate: "下一个扣帐日期",
      billSubtotal: "现有订阅余额",
      billTotal: "应付金额",
      billTotalDesc: ["自动扣账额将在余额消耗完毕后恢复原本订阅价格", ""],
      couponTitle: "促销代码",
      couponPlaceholder: "在此处输入促销代码",
      couponButton: ["输入", "取消"],
      couponWarning: "促销代码无效!",
    },

    subscribenows: {
      ltitle: "此为付费功能",
      ltitle_last: "您已完成探索我们的付费功能！",
      ldesc: "请升级你的订阅计划",
      rtitle: "解锁更多专业功能",
      rtitle1: "浏览所有网红账户数据分析",
      rdesc1: "轻松将网红数据列表汇出为Excel/PDF",
      rtitle2: "无限量创建行销活动",
      rdesc2: "快捷地定制您的行销活动",
      rtitle3: "无限量网红合作数量",
      rdesc3: "随时获得网红推荐、报价和合作，不受配额限制",
      rtitle4: "发掘网红排行榜及每周热门网红",
      rdesc4: "紧贴不同国家和社交平台上的热门网红",
      rtitle5: "一站式行销活动管理系统",
      rdesc5:
        "系统自动更新活动状态 - 管理报价、寄送产品、批核初稿和收集已发布帖子连接，省去繁复的步骤",
      rtitle6: "无限量网红搜寻",
      rtitle7: "无限量限关键字搜寻",
      maybelater: "暫不需要",
    },
  },
});
